import jsPDF from 'jspdf'

export default function ReportGenerator({ incident }) {
  const generatePDF = () => {
    const doc = new jsPDF()
    const caseId = `SL-${Date.now()}`

    doc.setFontSize(18)
    doc.setTextColor(30, 30, 200)
    doc.text('SAATCHI INCIDENT REPORT', 105, 20, { align: 'center' })

    doc.setFontSize(10)
    doc.setTextColor(100)
    doc.text('Your Digital Witness — Tamper-Proof Evidence', 105, 28, { align: 'center' })

    doc.setDrawColor(200)
    doc.line(20, 32, 190, 32)

    doc.setFontSize(11)
    doc.setTextColor(0)
    const fields = [
      ['Case ID', caseId],
      ['Generated On', new Date().toLocaleString()],
      ['Platform', incident.platform],
      ['Incident URL', incident.url],
      ['Captured At', new Date(incident.timestamp).toLocaleString()],
      ['Sender', incident.sender_name || 'Unknown'],
      ['Description', incident.description || 'No description provided'],
      ['SHA-256 Hash', incident.sha256_hash],
      ['Integrity Status', 'TAMPER-PROOF ✓'],
    ]

    let y = 45
    fields.forEach(([label, value]) => {
      doc.setTextColor(100)
      doc.text(`${label}:`, 20, y)
      doc.setTextColor(0)
      doc.text(`${value}`, 70, y, { maxWidth: 120 })
      y += 12
    })

    doc.setDrawColor(200)
    doc.line(20, y, 190, y)
    y += 10

    doc.setFontSize(9)
    doc.setTextColor(130)
    doc.text(
      'This report was auto-generated by SAATCHI Digital Witness. Evidence integrity is cryptographically verified.',
      105, y, { align: 'center', maxWidth: 160 }
    )

    doc.save(`SAATCHI_Report_${caseId}.pdf`)
  }

  return (
    <div className="bg-gray-900 rounded-2xl p-6 space-y-4">
      <div className="space-y-2">
        {[
          ['Platform', incident.platform],
          ['URL', incident.url],
          ['Captured At', new Date(incident.timestamp).toLocaleString()],
          ['Sender', incident.sender_name || 'Unknown'],
          ['SHA-256', incident.sha256_hash],
        ].map(([label, value]) => (
          <div key={label} className="flex gap-3">
            <span className="text-gray-400 w-28 shrink-0">{label}:</span>
            <span className="text-white text-sm break-all">{value}</span>
          </div>
        ))}
      </div>
      <button
        onClick={generatePDF}
        className="w-full bg-blue-600 p-3 rounded-xl font-semibold hover:bg-blue-700 mt-4"
      >
        ⬇️ Download Legal PDF Report
      </button>
    </div>
  )
}